/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.substring;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import org.junit.jupiter.api.Test;

class FindingSubstringTest {

  @Test
  void stringTest() throws IOException {
    String fileName = "./src/test/resources/string.txt";
    String subString = "aabaa";
    int[] beginning_array = {0, 3, 8, 11};
    ArrayList<Integer> beginning_list = new ArrayList<>();
    for (int j : beginning_array) {
      beginning_list.add(j);
    }
    Reader fileReader = new FileReader(fileName);
    assertEquals(beginning_list, Substring.findingSubstring(subString, fileReader));
  }

  @Test
  void noSubstringTest() throws IOException {
    String fileName = "./src/test/resources/string.txt";
    String subString = "abb";
    ArrayList<Integer> beginning_list = new ArrayList<>();
    Reader fileReader = new FileReader(fileName);
    assertEquals(beginning_list, Substring.findingSubstring(subString, fileReader));
  }

  @Test
  void someStringTest() throws IOException {
    String fileName = "./src/test/resources/someString.txt";
    String subString = "ABCDE";
    int[] beginning_array = {3, 14};
    ArrayList<Integer> beginning_list = new ArrayList<>();
    for (int j : beginning_array) {
      beginning_list.add(j);
    }
    Reader fileReader = new FileReader(fileName);
    assertEquals(beginning_list, Substring.findingSubstring(subString, fileReader));
  }
}
