/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.snake;

import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javafx.animation.Animation;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.*;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.Slider;
import javafx.scene.image.Image;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.util.Duration;
import javafx.util.StringConverter;

public class Main extends Application {

  private static final int WIDTH = 600;
  private static final int HEIGHT = WIDTH;
  private static int ROWS = 20;
  private static int COLUMNS = ROWS;
  private static final int SQUARE_SIZE = WIDTH / ROWS;

  private static final int RIGHT = 0;
  private static final int LEFT = 1;
  private static final int UP = 2;
  private static final int DOWN = 3;

  private GraphicsContext gc;
  private final List<Point> snakeBody = new ArrayList<>();
  private Point snakeHead;
  private int foodX;
  private int foodY;
  private Circle food;
  private boolean gameOver;
  private int currentDirection;
  private int score = 0;
  BorderPane root = new BorderPane();
  Scene scene;
  VBox menuBox;
  int easy;
  int hard;
  private final Canvas canvas = new Canvas(WIDTH, HEIGHT);

  @Override
  public void start(Stage primaryStage) {
    primaryStage.setTitle("Snake");
    VBox menu = new VBox();
    menu.setAlignment(Pos.CENTER);
    Button start = new Button("Start");
    start.setPrefSize(100, 20);
    Button settings = new Button("Settings");
    settings.setPrefSize(100, 20);
    Button exit = new Button("Exit");
    exit.setPrefSize(100, 20);
    menu.getChildren().addAll(start, settings, exit);
    root.setCenter(menu);
    scene = new Scene(root, WIDTH, HEIGHT);

    gc = canvas.getGraphicsContext2D();
    scene.setOnKeyPressed(event -> {
      KeyCode code = event.getCode();
      if (code == KeyCode.RIGHT || code == KeyCode.D) {
        if (currentDirection != LEFT) {
          currentDirection = RIGHT;
        }
      } else if (code == KeyCode.LEFT || code == KeyCode.A) {
        if (currentDirection != RIGHT) {
          currentDirection = LEFT;
        }
      } else if (code == KeyCode.UP || code == KeyCode.W) {
        if (currentDirection != DOWN) {
          currentDirection = UP;
        }
      } else if (code == KeyCode.DOWN || code == KeyCode.S) {
        if (currentDirection != UP) {
          currentDirection = DOWN;
        }
      }
    });

    for (int i = 0; i < 3; i++) {
      snakeBody.add(new Point(5, ROWS / 2));
    }
    snakeHead = snakeBody.get(0);
    generateFood(gc);

    Text gameDifficulty = new Text("Game Difficulty");
    Slider slider = new Slider(1, 3, 1);

    Text fieldSize = new Text("Field Size");
    Slider field = new Slider(1, 3, 1);

    primaryStage.setScene(scene);
    primaryStage.show();
    start.setOnAction(event -> {
      root.getChildren().remove(menu);
      root.getChildren().add(canvas);
      //scene.setRoot(canvas.getParent());
      int time = 300;
      if (slider.getValue() == 1d) {
        time = 300;
      } else if (slider.getValue() == 2d) {
        time = 200;
      } else if (slider.getValue() == 3d) {
        time = 100;
      }

      if (field.getValue() == 1d) {
        ROWS = 10;
        COLUMNS = 10;
      } else if (field.getValue() == 2d) {
        ROWS = 20;
        COLUMNS = 20;
      } else if (field.getValue() == 3d) {
        ROWS = 30;
        COLUMNS = 30;
      }
      Timeline timeline = new Timeline(new KeyFrame(Duration.millis(time), e -> run(gc)));
      timeline.setCycleCount(Animation.INDEFINITE);
      timeline.play();
      //startGame(primaryStage);
    });

    Button back = new Button("Back");
    VBox settingsMenu = new VBox();
    slider.setMinorTickCount(0);
    slider.setMajorTickUnit(1);
    slider.setSnapToTicks(true);
    slider.setShowTickMarks(true);
    slider.setShowTickLabels(true);
    slider.setPrefWidth(200);
    slider.setMaxWidth(200);
    slider.setMinWidth(200);
    slider.setLabelFormatter(new StringConverter<>() {
      @Override
      public String toString(Double object) {
        if (object == 1d) {
          return "Easy";
        } else if (object == 2d) {
          return "Medium";
        } else if (object == 3d) {
          return "Hard";
        }
        return "Hard";
      }

      @Override
      public Double fromString(String string) {
        return switch (string) {
          case "Easy" -> 1d;
          case "Medium" -> 2d;
          default -> 3d;
        };
      }
    });


    field.setMinorTickCount(0);
    field.setMajorTickUnit(1);
    field.setSnapToTicks(true);
    field.setShowTickMarks(true);
    field.setShowTickLabels(true);
    field.setPrefWidth(200);
    field.setMaxWidth(200);
    field.setMinWidth(200);
    field.setLabelFormatter(new StringConverter<>() {
      @Override
      public String toString(Double object) {
        if (object == 1d) {
          return "10x10";
        } else if (object == 2d) {
          return "20x20";
        } else if (object == 3d) {
          return "30x30";
        }
        return "30x30";
      }

      @Override
      public Double fromString(String string) {
        return switch (string) {
          case "10x10" -> 1d;
          case "20x20" -> 2d;
          default -> 3d;
        };
      }
    });

    settingsMenu.getChildren().addAll(gameDifficulty, slider, fieldSize, field, back);
    settingsMenu.setAlignment(Pos.CENTER);
    settings.setOnAction(event -> {
      root.getChildren().remove(menu);
      root.setCenter(settingsMenu);
    });

    back.setOnAction(event -> {
      root.getChildren().remove(settingsMenu);
      root.setCenter(menu);
    });

    exit.setOnAction(event -> {
      Platform.exit();
    });
  }

  public void startGame(Stage primaryStage) {
    scene.setRoot(canvas.getParent());
    //primaryStage.setScene(scene);
    //primaryStage.show();
    gc = canvas.getGraphicsContext2D();

    scene.setOnKeyPressed(event -> {
      KeyCode code = event.getCode();
      if (code == KeyCode.RIGHT || code == KeyCode.D) {
        if (currentDirection != LEFT) {
          currentDirection = RIGHT;
        }
      } else if (code == KeyCode.LEFT || code == KeyCode.A) {
        if (currentDirection != RIGHT) {
          currentDirection = LEFT;
        }
      } else if (code == KeyCode.UP || code == KeyCode.W) {
        if (currentDirection != DOWN) {
          currentDirection = UP;
        }
      } else if (code == KeyCode.DOWN || code == KeyCode.S) {
        if (currentDirection != UP) {
          currentDirection = DOWN;
        }
      }
    });

    for (int i = 0; i < 3; i++) {
      snakeBody.add(new Point(5, ROWS / 2));
    }
    snakeHead = snakeBody.get(0);
    generateFood(gc);
    Timeline timeline = new Timeline(new KeyFrame(Duration.millis(130), e -> run(gc)));
    timeline.setCycleCount(Animation.INDEFINITE);
    timeline.play();
  }

  private void run(GraphicsContext gc) {
    if (gameOver) {
      gc.setFill(Color.RED);
      gc.setFont(new Font("Digital-7", 70));
      gc.fillText("Game Over", WIDTH / 5, HEIGHT / 2);
      return;
    }
    drawBackground(gc);
    drawFood();
    drawSnake(gc);
    drawScore();
    for (int i = snakeBody.size() - 1; i >= 1; i--) {
      snakeBody.get(i).x = snakeBody.get(i - 1).x;
      snakeBody.get(i).y = snakeBody.get(i - 1).y;
    }

    switch (currentDirection) {
      case RIGHT -> moveRight();
      case LEFT -> moveLeft();
      case UP -> moveUp();
      case DOWN -> moveDown();
    }
    gameOver();
    eatFood();
  }

  private void drawBackground(GraphicsContext gc) {
    for (int i = 0; i < ROWS; i++) {
      for (int j = 0; j < COLUMNS; j++) {
        if ((i + j) % 2 == 0) {
          gc.setFill(Color.rgb(170, 215, 81));
        } else {
          gc.setFill(Color.rgb(162, 209, 73));
        }
        gc.fillRect(i * SQUARE_SIZE, j * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE);
      }
    }
  }

  private void generateFood(GraphicsContext gc) {
    start:
    while (true) {
      foodX = (int) (Math.random() * ROWS);
      foodY = (int) (Math.random() * COLUMNS);
      for (Point snake : snakeBody) {
        if (snake.getX() == foodX && snake.getY() == foodY) {
          continue start;
        }
      }
      //food = new Circle(foodX * SQUARE_SIZE + (SQUARE_SIZE / 2),
      //  foodY * SQUARE_SIZE + (SQUARE_SIZE / 2), SQUARE_SIZE / 2 - 1,
      //Color.rgb(242, 242, 37));

      //gc.setFill(Color.rgb(242, 242, 37));
      //gc.fillRoundRect(foodX * SQUARE_SIZE, foodY * SQUARE_SIZE, SQUARE_SIZE - 1, SQUARE_SIZE - 1,
      //  35, 35);
      break;
    }
  }

  private void drawFood() {
    gc.setFill(Color.rgb(242, 242, 37));
    gc.fillRoundRect(foodX * SQUARE_SIZE, foodY * SQUARE_SIZE, SQUARE_SIZE - 1, SQUARE_SIZE - 1,
        35, 35);
    //root.getChildren().add(food);
  }

  private void drawSnake(GraphicsContext gc) {
    gc.setFill(Color.rgb(200, 30, 30));
    gc.fillRoundRect(snakeHead.getX() * SQUARE_SIZE, snakeHead.getY() * SQUARE_SIZE,
        SQUARE_SIZE - 1, SQUARE_SIZE - 1, 20, 20);
    gc.setFill(Color.rgb(30, 30, 200));
    for (int i = 1; i < snakeBody.size(); i++) {
      gc.fillRoundRect(snakeBody.get(i).getX() * SQUARE_SIZE, snakeBody.get(i).getY() * SQUARE_SIZE,
          SQUARE_SIZE - 1, SQUARE_SIZE - 1, 20, 20);
    }
  }

  private void moveRight() {
    snakeHead.x++;
  }

  private void moveLeft() {
    snakeHead.x--;
  }

  private void moveUp() {
    snakeHead.y--;
  }

  private void moveDown() {
    snakeHead.y++;
  }

  private void gameOver() {
    if (snakeHead.x < 0 || snakeHead.y < 0 || snakeHead.x * SQUARE_SIZE >= WIDTH
        || snakeHead.y * SQUARE_SIZE >= HEIGHT) {
      gameOver = true;
    }
    for (int i = 1; i < snakeBody.size(); i++) {
      if (snakeHead.getX() == snakeBody.get(i).getX() && snakeHead.getY() == snakeBody.get(i).getY()) {
        gameOver = true;
        break;
      }
    }
  }
  private void eatFood() {
    if(snakeHead.getX() == foodX && snakeHead.getY() == foodY) {
      snakeBody.add(new Point(-1, -1));
      generateFood(gc);
      score += 5;
    }
  }
  private void drawScore() {
    gc.setFill(Color.WHITE);
    gc.setFont(new Font("Digital-7", 25));
    gc.fillText("Score: " + score, 10, 35);
  }
}
