/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.pizzeria;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

class PizzeriaTest {

  @Test
  void pizzeriaTest() {
    URL path = getClass().getClassLoader().getResource("Config.json");
    assert path != null;
    Pizzeria pizzeria = new Pizzeria(path.getPath());
    pizzeria.startWork();
    List<Client> clients = new ArrayList<>();
    for (int i = 0; i < 5; i++) {
      clients.add(new Client(pizzeria));
      clients.get(i).start();
    }
    for (Client client : clients) {
      try {
        client.join();
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }
    pizzeria.finishWork();
  }
}
