/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.pizzeria;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

class PizzeriaTest {

  @Test
  void pizzeriaTest() {
    Pizzeria pizzeria = new Pizzeria("C:\\Rep\\OOP\\Task_2_2_1\\lib\\src\\main\\resources\\Config.json");
    pizzeria.startWork();
    List<Client> clients = new ArrayList<>();
    for (int i = 0; i < 3; i++) {
      clients.add(new Client(pizzeria));
    }
    for (Client client : clients) {
      client.start();
    }
    for (Client client : clients) {
      try {
        client.join();
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
      pizzeria.createPoisonPillOrder();
    }
  }
}
