/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.heapsort;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import java.util.Arrays;
import org.junit.jupiter.api.Test;
import java.util.Random;

class HeapsortTest {

  @Test
  void test_1() {
    int[] initArray = {};
    int[] sortArray = {};
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }

  @Test
  void test_2() {
    int[] initArray = {3};
    int[] sortArray = {3};
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }

  @Test
  void test_3() {
    int[] initArray = {5, 4, 3, 2, 1};
    int[] sortArray = {1, 2, 3, 4, 5};
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }

  @Test
  void test_4() {
    int[] initArray = {3, 3, 1, 6, 4, 1};
    int[] sortArray = {1, 1, 3, 3, 4, 6};
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }

  @Test
  void test_5() {
    int[] initArray = {1, 2, 3, 4, 5, 6, 7};
    int[] sortArray = {1, 2, 3, 4, 5, 6, 7};
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }

  @Test
  void test_6() {
    Random rand = new Random();
    int[] initArray = new int[1000000];
    int[] sortArray = new int[1000000];
    for (int i = 0; i < 1000000; i++) {
      initArray[i] = rand.nextInt();
      sortArray[i] = initArray[i];
    }
    Arrays.sort(sortArray);
    Heapsort.sort(initArray);
    assertArrayEquals(sortArray, initArray, "Not equal!");
  }
}
