/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.pizzeria;

public class Client extends Thread {

  Pizzeria pizzeria;

  public Client(Pizzeria pizzeria) {
    this.pizzeria = pizzeria;
  }

  @Override
  public void run() {
    try {
      pizzeria.orderPizza();
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
