/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.pizzeria;

public class Client implements Runnable {

  @Override
  public void run() {
    try {
      Pizzeria.orderPizza();
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
