/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.tree;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class TreeTests {


  @Test
  void addRoot() {
    Tree<String> treeA = new Tree<>();
    treeA.add("A");
    assertEquals()
  }

}
