/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.vtatarintsev.substring;

import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

public class Substring {

  public void findingSubstring(String substring, String fileName) {
    try (FileReader fileReader = new FileReader(fileName)) {
      ArrayList<Integer> beginningSubstring = new ArrayList<>();
      int text_element_counter = 0;
      char[] buffer = new char[substring.length()];
      int[] prefix_function_substring = new int[substring.length()];
      prefix_function_substring[0] = 0;
      int j = 0;
      int i = 1;
      while (i != substring.length()) {
        if (substring.indexOf(i) == substring.indexOf(j)) {
          prefix_function_substring[i] = j + 1;
          i++;
          j++;
        } else if (j == 0) {
          prefix_function_substring[i] = 0;
          i++;
        } else {
          j = prefix_function_substring[j - 1];
        }
      }
      int lengthBuffer;
      while ((lengthBuffer = fileReader.read(buffer)) > 0) {
        if (lengthBuffer < buffer.length) {
          buffer = Arrays.copyOf(buffer, lengthBuffer);
        }
        int k = 0;
        int l = 0;
        while (k != buffer.length) {
          if (substring.indexOf(l) == buffer[k]) {
            k++;
            l++;
            text_element_counter++;
            if (l == substring.length()) {
              beginningSubstring.add(text_element_counter - l);
            }
          } else {
            if (l == 0) {
              k++;
              text_element_counter++;
            } else {
              l = prefix_function_substring[l - 1];
            }
          }
        }
      }
      System.out.println(beginningSubstring);
    } catch (IOException ex) {
      System.out.println(ex.getMessage());
    }
  }
}