/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.fit.vtatarintsev.heapsort;

/**
 * Heapsort class is needed to sort arrays.
 */
public class Heapsort {

  public static int i;
  public static int v1;
  public static int v2;
  public static int n;

  /**
   * Main method.
   *
   * @param array is array to sort.
   */
  public static void sort(int[] array) {
    for (i = 0; i < array.length; i++) {
      v1 = i;
      v2 = (i - 1) / 2;
      Utils.siftUp(array);
    }
    n = array.length;
    while (n > 1) {
      v1 = 0;
      v2 = n - 1;
      Utils.swap(array);
      n -= 1;
      Utils.siftDown(array);
    }

  }
}
